import { existsSync, readFileSync, writeFileSync } from "node:fs";

const faviconPath = "public/favicon.ico";

if (!existsSync(faviconPath)) {
  console.warn(`Favicon not found at ${faviconPath}, skipping.`);
  writeFileSync(
    "src/server/renderer/favicon.js",
    `// Auto-generated by scripts/build-favicon.mjs — do not edit
export const faviconBase64 = null;
`,
  );
  process.exit(0);
}

const buf = readFileSync(faviconPath);
const base64 = buf.toString("base64");

const output = `// Auto-generated by scripts/build-favicon.mjs — do not edit
export const faviconBase64 = ${JSON.stringify(base64)};
`;

writeFileSync("src/server/renderer/favicon.js", output);
console.log("Favicon generated: src/server/renderer/favicon.js");
