import { writeFileSync } from "node:fs";
import { build } from "esbuild";

const result = await build({
  entryPoints: ["src/client/entry.tsx"],
  bundle: true,
  format: "iife",
  minify: true,
  write: false,
  target: "es2022",
  tsconfig: "tsconfig.client.json",
  jsx: "automatic",
  jsxImportSource: "preact",
});

if (!result.outputFiles?.[0]) {
  console.error("Build produced no output files");
  process.exit(1);
}
const code = result.outputFiles[0].text;

const moduleContent = `// Auto-generated by scripts/build-client.mjs — do not edit
export const clientBundle = ${JSON.stringify(code)};
`;

writeFileSync("src/renderer/client-bundle.js", moduleContent);
console.log("Client bundle generated: src/renderer/client-bundle.js");
