import { writeFileSync } from "node:fs";
import { build } from "esbuild";

const result = await build({
  entryPoints: ["src/client/index.ts"],
  bundle: true,
  format: "iife",
  minify: true,
  write: false,
  target: "es2022",
  tsconfig: "tsconfig.client.json",
});

const code = result.outputFiles[0].text;

const output = `// Auto-generated by scripts/build-client.mjs — do not edit
export const clientBundle = ${JSON.stringify(code)};
`;

writeFileSync("src/generated/client-bundle.ts", output);
console.log("Client bundle generated: src/generated/client-bundle.ts");
